### ISSUE TITLE
Unnecessary Accessibility Control [macos]

### ISSUE THREAD

**Issue by obisims** [fredericocurti/magneto#2]
Why does this application request access to control computer on macos? that seems invasive, i didn't investigate further but it seems odd.

**Comment by fredericocurti** [comment]
Does it? Only prompt I remember seeing was allow incoming connections which is necessary for the torrent component, can you repro or post a screen shot?

**Comment by obisims** [comment]
Yeah i got the incoming connection request but seperatley from this other one, i'll see if i can reproduce after dinner and finishing this vid i'm watching using it. It seemed to run fine without providing those permissions with the exception of no video, only audio when being cast from VLC to a chromecast.

cool repo btw

**Comment by obisims** [comment]
So i attempted to delete and reinstall but got neither permision request this time, only the unidentified developer security thing, pardon but i haven't had to deal with deleting previously approved permissions on macos so don't have a beat on how to do it fresh. if you know how and can advise without an os reinstall i'd be happy to take the sec.

some info for further context though.
1. The audio + no video issue seems to also be happening with local files cast through vlc so i doubt that had anything to do with your repo. just another annoying chromecast bug out of nowhere.
2. the request appeared simultaneously with the 'allow incoming requests' dialog.
3. It said something on the lines of 'Allow magneto to control your computer'
4. Upon clicking okay it opened up macos system preferences > security & privacy > privacy > and then i beleive brought me to the 'accesibility' subsection.
5. I am currently on a 15-inch 2019 macbook pro running macos monterey 12.6, 16gb ddr4 memory, 2.3GHz 8-core intel i9

**Comment by fredericocurti** [comment]
Unfortunately I wasn't able to reproduce it myself either. I've tried running
`tccutil reset All com.magneto.client` to clear permissions, removed and download fresh .app file, but still.

I don't think I'll have the bandwidth to dig much deeper into this for now, if you have any privacy concerns feel free to build the binary yourself via xcode, the code is very simple :)
